function _objectWithoutPropertiesLoose(e,a){if(null==e)return{};
var t,l,n={},
o=Object.keys(e);
for(l=0;l<o.length;l++)t=o[l],
a.indexOf(t)>=0||(n[t]=e[t]);
return n}var _excluded=["containerId"],
VideoSDKMeeting=function(){function e(){}var a=e.prototype;
return a.init=function(e){var a=void 0===e?{}:e,
t=a.containerId,
l=_objectWithoutPropertiesLoose(a,_excluded);
try{var n=parent.document,o=parent.window;
if(void 0===o||void 0===n)throw Error("No browser detected!");
return Promise.resolve(this.generatePrebuiltSrc(l,o,n)).then(function(e){var a=n.createElement("iframe");
a.id="videosdk-frame",
a.src=e,a.allowfullscreen=!0,
a.width="100%",
a.height="100%",
a.allow="camera *; microphone *; fullscreen; display-capture; allow-same-origin; allow-presentation; encrypted-media; midi; encrypted-media ",
a.style.border=0,a.allowusermedia="allowusermedia";
var l=null;
if(t){var r=n.getElementById(t);
if(!r)throw Error("No Container found with id "+t);
l=r,r.appendChild(a)}else{var i=n.createElement("div");
i.style.position="fixed",
i.style.left=0,
i.style.right=0,
i.style.bottom=0,
i.style.top=0,
l=i,
i.appendChild(a),
n.body.style.margin="0px",
n.body.style.padding="0px",
n.body.style.height="100%",
n.body.style.overflow="hidden",
n.body.appendChild(i)}o.addEventListener("popstate",function(e){l.remove()})})}catch(r){return Promise.reject(r)}},
a.fetchToken=function(e){
    var a=e.apiKey,
    t=e.askJoin,
    l=e.apiBaseUrl;
    try{
        var n=[];t?n.push("ask_join"):n.push("allow_join");
        var o={apiKey:a};
        return n.length&&(o.permissions=n),
        Promise.resolve(fetch((l||"https://api.videosdk.live")+"/v1/prebuilt/token",
        {method:"POST",headers:{"Content-type":"application/json"},
        body:JSON.stringify(o)})).then(function(e){var a,t=function(){if(200===e.status)return Promise.resolve(e.json()).then(function(e){a=e.token});
        throw Error("Could not fetch token.")}();
        return t&&t.then?t.then(function(e){return a}):a})}catch(r){return Promise.reject(r)}},
        a.generatePrebuiltSrc=function(e,a){var t=void 0===e?{}:e,
        l=t.name,
        n=t.apiKey,
        o=t.meetingId,
        r=t.token,
        i=t.region,
        u=t.preferredProtocol,
        y=t.redirectOnLeave,
        d=t.micEnabled,
        s=t.webcamEnabled,
        c=t.participantCanToggleSelfWebcam,
        v=t.participantCanToggleSelfMic,
        p=t.participantTabPanelEnabled,
        f=t.participantCanLeave,
        b=t.chatEnabled,
        k=t.screenShareEnabled,
        g=t.pollEnabled,
        h=t.whiteboardEnabled,
        m=t.raiseHandEnabled,
        S=t.theme,
        E=t.branding,
        w=t.livestream,
        T=t.recording,
        $=t.hls,
        P=t.waitingScreen,
        C=t.permissions,
        L=t.joinScreen,
        U=t.leftScreen,
        j=t.layout,
        O=t.maxResolution,
        A=t.debug,
        B=t.isRecorder,
        W=t.maintainVideoAspectRatio,
        R=t.networkBarEnabled,
        M=t.participantId,
        D=t.meetingLayoutTopic,
        I=t.joinWithoutUserInteraction,
        x=t.notificationSoundEnabled,
        _=t.notificationAlertsEnabled,
        K=t.animationsEnabled,
        V=t.topbarEnabled,
        H=t.hideLocalParticipant,
        z=t.alwaysShowOverlay,
        F=t.sideStackSize,
        J=t.reduceEdgeSpacing,
        N=t.embedBaseUrl,
        G=t.apiBaseUrl,
        Y=t.mode;
        try{var q=function(e){r=e;var t,n=null==a?void 0:null===(t=a.navigator)||void 0===t?void 0:t.userAgent,
            E=[
                {key:"micEnabled",value:d?"true":"false"},
                {key:"webcamEnabled",value:s?"true":"false"},
                {key:"name",value:l},
                {key:"meetingId",value:o||""},
                {key:"region",value:i||"sg001"},
                {key:"preferredProtocol",value:u||"UDP_ONLY"},
                {key:"canChangeLayout",value:es?"true":"false"},
                {key:"meetingId",value:o||""},
                {key:"redirectOnLeave",value:y||""},
                {key:"chatEnabled",value:b?"true":"false"},
                {key:"theme",value:S||"DEFAULT"},
                {key:"screenShareEnabled",value:k?"true":"false"},
                {key:"pollEnabled",value:"boolean"==typeof g?g?"true":"false":"true"},
                {key:"whiteboardEnabled",value:h?"true":"false"},
                {key:"participantCanToggleSelfWebcam",value:c?"true":"false"},
                {key:"participantCanToggleSelfMic",value:v?"true":"false"},
                {key:"raiseHandEnabled",value:m?"true":"false"},
                {key:"token",value:r||""},
                {key:"recordingEnabled",value:eD?"true":"false"},
                {key:"recordingWebhookUrl",value:eI||""},
                {key:"recordingAWSDirPath",value:ex||""},
                {key:"autoStartRecording",value:e_?"true":"false"},
                {key:"recordingTheme",value:eK||"DEFAULT"},
                {key:"participantCanToggleRecording",value:"boolean"==typeof ei&&(ei?"true":"false")},
                {key:"brandingEnabled",value:eN?"true":"false"},{key:"brandLogoURL",value:eG||""},
                {key:"brandName",value:eY},{key:"participantCanLeave",value:"boolean"==typeof f?f?"true":"false":"true"},
                {key:"poweredBy",value:"boolean"==typeof e0?e0?"true":"false":"true"},
                {key:"liveStreamEnabled",value:ef?"true":"false"},
                {key:"autoStartLiveStream",value:eb?"true":"false"},
                {key:"liveStreamOutputs",value:JSON.stringify(ek||[])},
                {key:"liveStreamTheme",value:eg||"DEFAULT"},
                {key:"participantCanToggleOtherMic",value:ee?"true":"false"},
                {key:"participantTabPanelEnabled",value:"boolean"==typeof p?p?"true":"false":"true"},
                {key:"partcipantCanToogleOtherScreenShare",value:ea?"true":"false"},
                {key:"participantCanToggleOtherWebcam",value:Z?"true":"false"},
                {key:"participantCanToggleOtherMode",value:et?"true":"false"},
                {key:"askJoin",value:X?"true":"false"},
                {key:"joinScreenEnabled",value:ew?"true":"false"},
                {key:"joinScreenMeetingUrl",value:eT||""},
                {key:"joinScreenTitle",value:e$||""},
                {key:"notificationSoundEnabled",value:"boolean"==typeof x?x?"true":"false":"true"},
                {key:"canPin",value:ed?"true":"false"},{key:"canCreatePoll",value:ec?"true":"false"},
                {key:"canToggleParticipantTab",value:"boolean"==typeof ev?ev?"true":"false":"true"},
                {key:"layoutType",value:eB},{key:"mode",value:Y},
                {key:"participantCanEndMeeting",value:"boolean"==typeof en&&en?"true":"false"},
                {key:"canDrawOnWhiteboard",value:"boolean"==typeof eo?eo?"true":"false":"true"},
                {key:"canToggleWhiteboard",value:"boolean"==typeof er?er?"true":"false":"true"},
                {key:"canRemoveOtherParticipant",value:"boolean"==typeof el&&el?"true":"false"},
                {key:"leftScreenActionButtonLabel",value:ej},
                {key:"leftScreenActionButtonHref",value:eO},
                {key:"maxResolution",value:O||"sd"},
                {key:"animationsEnabled",value:"boolean"!=typeof K||K},
                {key:"topbarEnabled",value:"boolean"!=typeof V||V},
                {key:"notificationAlertsEnabled",value:"boolean"!=typeof _||_},
                {key:"debug",value:"boolean"==typeof A&&A},
                {key:"participantId",value:M||""},
                {key:"layoutPriority",value:eW||""},
                {key:"layoutGridSize",value:eR||"0"},
                {key:"hideLocalParticipant",value:"boolean"==typeof H&&H?"true":"false"},
                {key:"alwaysShowOverlay",value:"boolean"==typeof z&&z?"true":"false"},
                {key:"sideStackSize",value:F},
                {key:"reduceEdgeSpacing",value:"boolean"==typeof J&&J?"true":"false"},
                {key:"isRecorder",value:"boolean"==typeof B&&B?"true":"false"},
                {key:"maintainVideoAspectRatio",value:"boolean"==typeof W?W?"true":"false":"true"},
                {key:"networkBarEnabled",value:"boolean"==typeof R?R?"true":"false":"true"},
                {key:"leftScreenRejoinButtonEnabled",value:"boolean"==typeof eL?eL?"true":"false":"true"},
                {key:"joinWithoutUserInteraction",value:"boolean"==typeof I&&I?"true":"false"},
                {key:"rawUserAgent",value:n||""},{key:"meetingLayoutTopic",value:D||""},
                {key:"canChangeLayout",value:"boolean"==typeof es&&es?"true":"false"},
                {key:"participantCanToggleLivestream",value:"boolean"==typeof eu&&eu?"true":"false"},
                {key:"hlsEnabled",value:e8?"true":"false"},{key:"autoStartHls",value:eH?"true":"false"},
                {key:"participantCanToggleHls",value:"boolean"==typeof ey&&ey?"true":"false"},
                {key:"hlsPlayerControlsVisible",value:"boolean"==typeof ez&&ez?"true":"false"},
                {key:"hlsTheme",value:eF||"DEFAULT"},{key:"waitingScreenImageUrl",value:em||""},
                {key:"waitingScreenText",value:eS||""}].
                map(function(e){
                    var a=e.key,t=e.value;
                    return a+"="+encodeURIComponent(t)}).join("&");
                    return(N||"https://embed.videosdk.live/rtc-js-prebuilt/0.3.19/")+"/?"+E};w||(w={}),C||(C={}),L||(L={}),U||(U={}),j||(j={}),T||(T={}),$||($={}),P||(P={}),E||(E={});
                    var Q=C,X=Q.askToJoin,Z=Q.toggleParticipantWebcam,ee=Q.toggleParticipantMic,ea=Q.toggleParticipantScreenshare,et=Q.toggleParticipantMode,el=Q.removeParticipant,en=Q.endMeeting,eo=Q.drawOnWhiteboard,er=Q.toggleWhiteboard,ei=Q.toggleRecording,eu=Q.toggleLivestream,ey=Q.toggleHls,ed=Q.pin,es=Q.changeLayout,ec=Q.canCreatePoll,ev=Q.canToggleParticipantTab;
                    X&&(Z=!1,ee=!1,ea=!1);
                    var ep=w,ef=ep.enabled,eb=ep.autoStart,ek=ep.outputs,eg=ep.theme,eh=P,em=eh.imageUrl,eS=eh.text,eE=L,ew=eE.visible,eT=eE.meetingUrl,e$=eE.title,eP=U,eC=eP.actionButton,eL=eP.rejoinButtonEnabled,eU=eC=eC||{},ej=eU.label,eO=eU.href,eA=j,eB=eA.type,eW=eA.priority,eR=eA.gridSize,eM=T,eD=eM.enabled,eI=eM.webhookUrl,ex=eM.awsDirPath,e_=eM.autoStart,eK=eM.theme,eV=$,e8=eV.enabled,eH=eV.autoStart,ez=eV.playerControlsVisible,eF=eV.theme,eJ=E,eN=eJ.enabled,eG=eJ.logoURL,eY=eJ.name,e0=eJ.poweredBy;
                    if(!r&&!n)throw Error('Any one of "token" or "apiKey" must be provided.');
                    var e1=r;
                    return Promise.resolve(e1?q(e1):Promise.resolve(this.fetchToken({apiKey:n,askJoin:X,apiBaseUrl:G})).then(q))}catch(e7){return Promise.reject(e7)}},e}();
                    exports.VideoSDKMeeting=VideoSDKMeeting;
